"""Tests for account confirmation token generation and verification."""

from app import db
from app.models import User


def test_confirm_token(app):
    """Token generated by get_confirm_token should validate to the same user."""
    with app.app_context():
        user = User(full_name="Token Tester", email="token@example.com")
        db.session.add(user)
        db.session.commit()

        token = user.get_confirm_token()
        assert User.verify_confirm_token(token) == user
        assert User.verify_confirm_token("invalid-token") is None
        assert User.verify_confirm_token(token, expires_sec=-1) is None
