"""Add session_type to user

Revision ID: 11045d5514ab
Revises: b7fee1a97eeb
Create Date: 2025-08-05 16:44:52.305433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11045d5514ab'
down_revision = 'b7fee1a97eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_type')

    # ### end Alembic commands ###
