"""Add document_recipient_email to user

Revision ID: 65ed717d04cb
Revises: 802bd0e84445
Create Date: 2025-08-05 12:35:42.574577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ed717d04cb'
down_revision = '802bd0e84445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_recipient_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('document_recipient_email')

    # ### end Alembic commands ###
