"""allow duplicate user full names

Revision ID: 802bd0e84445
Revises: ff08420f51db
Create Date: 2025-08-03 16:30:21.817399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802bd0e84445'
down_revision = 'ff08420f51db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_full_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_full_name', ['full_name'])

    # ### end Alembic commands ###
