"""initial

Revision ID: a53caae9ae42
Revises: 
Create Date: 2025-07-31 12:07:05.515176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53caae9ae42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('default_duration', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('beneficjent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=100), nullable=False),
    sa.Column('wojewodztwo', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zajecia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('godzina_od', sa.Time(), nullable=False),
    sa.Column('godzina_do', sa.Time(), nullable=False),
    sa.Column('specjalista', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zajecia_beneficjenci',
    sa.Column('zajecia_id', sa.Integer(), nullable=True),
    sa.Column('beneficjent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beneficjent_id'], ['beneficjent.id'], ),
    sa.ForeignKeyConstraint(['zajecia_id'], ['zajecia.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zajecia_beneficjenci')
    op.drop_table('zajecia')
    op.drop_table('beneficjent')
    op.drop_table('user')
    # ### end Alembic commands ###
