"""rename username to full_name

Revision ID: f134c9089658
Revises: a53caae9ae42
Create Date: 2025-07-31 22:51:06.571247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f134c9089658'
down_revision = 'a53caae9ae42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint('uq_user_full_name', ['full_name'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint('uq_user_full_name', type_='unique')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
